services:
  beszel:
    build:
      context: .
      dockerfile: Dockerfile
    image: beszel-local:dev
    container_name: beszel-local
    restart: unless-stopped
    environment:
      APP_URL: http://localhost:8090
    ports:
      - "8090:8090"
    volumes:
      - ./docker_data/beszel:/beszel_data

  beszel-agent:
    image: beszel-local:dev
    container_name: beszel-agent-local
    restart: unless-stopped
    depends_on:
      - beszel
    network_mode: host
    environment:
      DATA_DIR: /beszel_agent_data
      HUB_URL: http://127.0.0.1:8090
      TOKEN: f0ebe440-a912-4901-9585-d1df05997ed6
      KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqhb184cMxo9uJV/3X4WD2MnejGztVtdxZcSaj2cD3x
      LISTEN: 45877
      LOG_LEVEL: warn
    volumes:
      - ./docker_data/agent:/beszel_agent_data
    command: []
    entrypoint: ["/usr/local/bin/beszel-agent"]
